package testapp.core.exceptions;

public class UsernameAlreadyExistsException extends RuntimeException {
}
